"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BottleAnatomy, CinematicScroll, ThrowScroll } from "../components/ScrollBoutique";
import { GiftingStudio, ScentConcierge, ScentMap, SignatureQuiz, TrioBuilder } from "../components/BoutiqueTools";
import { catalog as staticCatalog, type CatalogItem, money } from "../lib/catalog";
import { createOrderDraft } from "../lib/order-draft-client";

const heroVideos=["/media/amber-oud.mp4","/media/royal-oud.mp4","/media/signature-story.mp4"];
async function openInstagram(message:string){try{await navigator.clipboard.writeText(message)}catch{}window.open("https://ig.me/m/skfragrances.in","_blank","noopener,noreferrer")}

export default function Home(){
  const [cart,setCart]=useState<Record<string,number>>({});
  const liveCatalog:CatalogItem[]=staticCatalog;
  const [cartOpen,setCartOpen]=useState(false);const [menu,setMenu]=useState(false);const [copied,setCopied]=useState(false);
  const [heroVideo,setHeroVideo]=useState(0);const [muted,setMuted]=useState(true);const [wishlist,setWishlist]=useState<string[]>([]);const [compare,setCompare]=useState<string[]>([]);
  const videoRefs=useRef<(HTMLVideoElement|null)[]>([]);
  const giftSets=liveCatalog.filter((item)=>item.kind==="Gift Set");
  const individualAttars=liveCatalog.filter((item)=>item.kind==="Individual Attar");
  const qty=Object.values(cart).reduce((sum,value)=>sum+value,0);const total=liveCatalog.reduce((sum,item)=>sum+item.price*(cart[item.id]||0),0);
  const compared=compare.map(id=>liveCatalog.find(item=>item.id===id)!).filter(Boolean);
  const message=useMemo(()=>`Hello Shah Kripa Fragrances! I would like to place a prepaid Instagram order:\n\n${liveCatalog.filter(item=>cart[item.id]).map(item=>`• ${item.name} (${item.series} · ${item.size}) × ${cart[item.id]} — ${money(item.price*cart[item.id])}`).join("\n")}\n\nListed total: ${money(total)}\nPlease confirm the exclusive Instagram discount, final prepaid amount and delivery details.`,[cart,total,liveCatalog]);
  useEffect(()=>{const saved=localStorage.getItem("skf-wishlist");if(saved)try{setWishlist(JSON.parse(saved))}catch{}},[]);
  useEffect(()=>{localStorage.setItem("skf-wishlist",JSON.stringify(wishlist))},[wishlist]);
  useEffect(()=>{document.body.style.overflow=cartOpen||menu?"hidden":"";return()=>{document.body.style.overflow=""}},[cartOpen,menu]);
  useEffect(()=>{const timer=window.setInterval(()=>setHeroVideo(value=>(value+1)%heroVideos.length),7500);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{videoRefs.current.forEach((video,index)=>{if(!video)return;video.muted=muted;if(index===heroVideo)video.play().catch(()=>{});else video.pause()})},[heroVideo,muted]);
  const add=(id:string)=>{const item=liveCatalog.find(product=>product.id===id);if(!item||item.stockStatus==="paused")return;setCart(current=>({...current,[id]:(current[id]||0)+1}));setCartOpen(true)};
  const update=(id:string,delta:number)=>setCart(current=>{const value=Math.max(0,(current[id]||0)+delta);const next={...current,[id]:value};if(!value)delete next[id];return next});
  const order=async()=>{if(!qty)return;const draft=await createOrderDraft(Object.entries(cart).map(([id,quantity])=>({id,quantity})),"instagram-bag");const finalMessage=draft?`${message}\n\nSKF order reference: ${draft.reference}`:message;try{await navigator.clipboard.writeText(finalMessage);setCopied(true)}catch{}window.open("https://ig.me/m/skfragrances.in","_blank","noopener,noreferrer")};
  const toggleWish=(id:string)=>setWishlist(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleCompare=(id:string)=>setCompare(current=>current.includes(id)?current.filter(value=>value!==id):current.length<3?[...current,id]:current);
  const remember=(id:string)=>{try{const current=JSON.parse(localStorage.getItem("skf-recent")||"[]") as string[];localStorage.setItem("skf-recent",JSON.stringify([id,...current.filter(value=>value!==id)].slice(0,4)))}catch{}};
  const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","name":"Shah Kripa Fragrances","alternateName":"SKF Attars","url":"https://www.skfragrances.in","logo":"https://www.skfragrances.in/media/logo-gold.webp","email":"skfragrances.in@gmail.com","taxID":"06ALEPD3412G1ZR","address":{"@type":"PostalAddress","streetAddress":"House No. 392, Sonia Colony, Manav Chowk","addressLocality":"Ambala","addressRegion":"Haryana","postalCode":"134003","addressCountry":"IN"},"sameAs":["https://www.instagram.com/skfragrances.in/"]},{"@type":"WebSite","name":"Shah Kripa Fragrances","url":"https://www.skfragrances.in","description":"Premium alcohol-free attars and attar gift sets in India."},{"@type":"ItemList","name":"SKF Attar Catalogue","numberOfItems":liveCatalog.length,"itemListElement":liveCatalog.map((item,index)=>({"@type":"ListItem","position":index+1,"url":`https://www.skfragrances.in/products/${item.id}`,"item":{"@type":"Product","name":item.name,"description":item.description,"image":`https://www.skfragrances.in${item.image}`,"brand":{"@type":"Brand","name":"Shah Kripa Fragrances"},"offers":{"@type":"Offer","priceCurrency":"INR","price":item.price,"availability":item.stockStatus==="paused"?"https://schema.org/OutOfStock":"https://schema.org/InStock","url":`https://www.skfragrances.in/products/${item.id}`}}}))}]};
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><div className="grain" aria-hidden="true"/>
    <header className="nav-wrap"><a className="brand" href="#top"><img src="/media/logo-gold.webp" alt=""/><span>SHAH KRIPA <small>FRAGRANCES</small></span></a><nav className={menu?"nav-links open":"nav-links"}><a href="#collection" onClick={()=>setMenu(false)}>Collections</a><a href="#individual-bottles" onClick={()=>setMenu(false)}>Attars</a><a href="#scent-finder" onClick={()=>setMenu(false)}>Scent finder</a><a href="#gifting" onClick={()=>setMenu(false)}>Gifting</a><a href="/journal" onClick={()=>setMenu(false)}>Journal</a></nav><div className="nav-actions"><button className="wishlist-nav" onClick={()=>document.getElementById("individual-bottles")?.scrollIntoView()}>Saved <span>{wishlist.length}</span></button><button className="cart-button" onClick={()=>setCartOpen(true)}>Bag <span>{qty}</span></button><button className="menu-button" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button></div></header>
    <section className="hero" id="top">{heroVideos.map((src,index)=><video ref={node=>{videoRefs.current[index]=node}} className={index===heroVideo?"active":""} key={src} autoPlay={index===0} muted={muted} loop playsInline preload={index===0?"auto":"metadata"} poster="/media/square/royal-oud-sq.webp"><source src={src} type="video/mp4"/></video>)}<div className="hero-wash"/><div className="hero-copy"><p className="kicker">Natural expression · Alcohol-free attars</p><h1>Wear what<br/><em>words cannot say.</em></h1><p className="hero-lede">Nine distinctive attars. Three curated worlds. One presence that remains.</p><div className="hero-cta"><a className="button primary" href="#scent-finder">Find your signature</a><a className="text-link light" href="#collection">Explore the house ↓</a></div></div><div className="hero-index"><span>0{heroVideo+1}</span><i/><span>03</span></div><div className="video-dots">{heroVideos.map((_,index)=><button className={index===heroVideo?"active":""} key={index} onClick={()=>setHeroVideo(index)} aria-label={`Play campaign film ${index+1}`}/>)}</div><a href="#fragrance-worlds" className="scroll-cue">Scroll <span>↓</span></a></section>
    <section className="promise-strip"><span>Alcohol-free</span><i/><span>3 × 6 ml gift sets</span><i/><span>Unisex compositions</span><i/><span>Prepaid Instagram savings</span></section>
    <div id="fragrance-worlds"><CinematicScroll/></div>
    <section className="collection section" id="collection"><div className="section-heading"><p className="kicker">The house collections</p><h2>Three worlds.<br/>One unforgettable signature.</h2><p>Each collection contains three 6 ml roll-on attars, selected to be worn alone or layered into something entirely personal.</p></div><div className="collection-cards">{giftSets.map((item,index)=><article className={`collection-card ${item.seriesId}`} id={`${item.seriesId}-collection`} key={item.id}><div className="collection-card-image"><img src={item.image} alt={`${item.name} three bottle gift set`}/><span>0{index+1}</span>{item.stockStatus!=="available"&&<em className={`stock-badge ${item.stockStatus}`}>{item.stockStatus==="paused"?"Temporarily unavailable":"Limited availability"}</em>}</div><div className="collection-card-copy"><p className="kicker">{item.mood}</p><h3>{item.name}</h3><p className="collection-scent">{item.scent}</p><p>{item.description}</p><div className="price-row"><strong>{money(item.price)}</strong><s>{money(item.mrp||0)}</s><span>{Math.round((1-item.price/(item.mrp||item.price))*100)}% off</span></div><small>{item.stockStatus==="paused"?"This collection is temporarily unavailable":item.stockStatus==="limited"?"Limited availability · Amazon price includes all taxes":"Amazon selling price · inclusive of all taxes"}</small><div className="card-actions">{item.stockStatus==="paused"?<button className="button dark" disabled>Temporarily unavailable</button>:<a className="button dark" href={item.amazon} target="_blank">Buy on Amazon ↗</a>}<a className="button outline" href={`/products/${item.id}`} onClick={()=>remember(item.id)}>Enter collection</a></div></div></article>)}</div><p className="amazon-note">Selling prices and availability may change on Amazon India. MRP is shown for comparison.</p></section>
    <SignatureQuiz products={giftSets}/>
    <section className="sku-marquee" aria-label="All fragrance products"><div className="marquee-heading"><span>Every signature in the house</span><a href="#individual-bottles">Explore all 12 SKUs ↓</a></div><div className="marquee-window"><div className="marquee-track">{[...liveCatalog,...liveCatalog].map((item,index)=><a className="marquee-card" href={`/products/${item.id}`} onClick={()=>remember(item.id)} key={`${item.id}-${index}`}><img src={item.image} alt=""/><div><span>{item.kind} · {item.size}</span><h2>{item.name}</h2><strong>{item.stockStatus==="paused"?"Temporarily unavailable":money(item.price)}</strong></div></a>)}</div></div></section>
    <section className="bottle-shop section" id="individual-bottles"><div className="bottle-shop-head"><div><p className="kicker">The individual wardrobe</p><h2>Every bottle,<br/>individually yours.</h2></div><p>Save favourites, compare fragrance character and enter a dedicated product page for every 6 ml attar.</p></div><div className="bottle-grid">{individualAttars.map((item,index)=><article className={`bottle-card ${item.stockStatus==="paused"?"is-paused":""}`} key={item.id}><div className="bottle-image"><span>0{index+1}</span><img src={item.image} alt={`${item.name} individual 6 ml alcohol-free attar bottle`} loading="lazy"/>{item.stockStatus!=="available"&&<em className={`stock-badge ${item.stockStatus}`}>{item.stockStatus==="paused"?"Temporarily unavailable":"Limited availability"}</em>}<div className="bottle-tools"><button className={wishlist.includes(item.id)?"active":""} onClick={()=>toggleWish(item.id)} aria-label={`${wishlist.includes(item.id)?"Remove":"Add"} ${item.name} ${wishlist.includes(item.id)?"from":"to"} wishlist`}>{wishlist.includes(item.id)?"♥":"♡"}</button><button className={compare.includes(item.id)?"active":""} onClick={()=>toggleCompare(item.id)} aria-label={`Compare ${item.name}`}>{compare.includes(item.id)?"✓":"↔"}</button></div></div><div className="bottle-copy"><small>{item.series} · {item.size}</small><h3>{item.name}</h3><p className="bottle-scent">{item.scent}</p><p>{item.description}</p><div><strong>{money(item.price)}</strong><button className="round-add" disabled={item.stockStatus==="paused"} onClick={()=>add(item.id)} aria-label={item.stockStatus==="paused"?`${item.name} is temporarily unavailable`:`Add ${item.name} to Instagram bag`}>{item.stockStatus==="paused"?"×":"+"}</button></div><a href={`/products/${item.id}`} onClick={()=>remember(item.id)}>Experience this attar →</a></div></article>)}</div><p className="single-note">Individual bottles are available through prepaid Instagram ordering. Gift sets remain available through Amazon and Instagram.</p>{compared.length>0&&<div className="compare-panel"><div className="compare-head"><div><p className="kicker">Fragrance comparison</p><h3>{compared.length} of 3 selected</h3></div><button onClick={()=>setCompare([])}>Clear</button></div><div className="compare-grid">{compared.map(item=><article key={item.id}><img src={item.image} alt=""/><h4>{item.name}</h4><span>{item.series}</span><dl><div><dt>Character</dt><dd>{item.mood}</dd></div><div><dt>Profile</dt><dd>{item.scent}</dd></div><div><dt>Best for</dt><dd>{item.occasion}</dd></div><div><dt>Price</dt><dd>{money(item.price)}</dd></div></dl><a href={`/products/${item.id}`}>View product →</a></article>)}</div></div>}</section>
    <ScentMap products={individualAttars}/><TrioBuilder products={individualAttars}/><ThrowScroll/><BottleAnatomy/>
    <section className="heritage-scroll section" id="craft"><div className="heritage-copy"><p className="kicker">Where our story began</p><h2>A presence<br/>that remained.</h2><p className="story-lead">Long before Shah Kripa Fragrances became a house of attars, fragrance was already part of the family’s language.</p><p>The founder’s grandfather wore attar with such distinction that his presence lingered after he had passed through a room. From metres away, family and friends could recognise his trail and know he had been there. That memory became our inspiration: fragrance should do more than smell beautiful—it should leave a signature.</p><blockquote>“Not merely a fragrance.<br/>A trace of who you are.”</blockquote></div><div className="heritage-film"><video autoPlay muted loop playsInline poster="/media/square/royal-oud-sq.webp"><source src="/media/signature-story.mp4" type="video/mp4"/></video><span>Essence of Nature. Purity of Attar.</span></div></section>
    <GiftingStudio/>
    <section className="unboxing section"><div className="unboxing-copy"><p className="kicker">The unboxing ritual</p><h2>Anticipation,<br/>designed into every layer.</h2><ol><li><b>01</b><span>The floral house box</span></li><li><b>02</b><span>The satin-soft presentation</span></li><li><b>03</b><span>Three 6 ml signatures revealed</span></li><li><b>04</b><span>Your personal message</span></li></ol></div><div className="unboxing-gallery"><img src="/media/square/sovereign-box-v2-sq.webp" alt="SKF luxury fragrance box"/><img src="/media/square/aura-inside-v2-sq.webp" alt="Aura Series bottles inside gift box"/><img src="/media/square/ethnic-box-sq.webp" alt="Ethnic Series gift packaging"/></div></section>
    <section className="reviews section" id="reviews"><div className="review-head"><div><p className="kicker">Verified marketplace response</p><h2>Small rituals.<br/>Strong impressions.</h2></div><div className="rating"><strong>5.0</strong><span>★★★★★</span><p>Current displayed average across the three Amazon listings</p></div></div><div className="rating-grid">{giftSets.map((item,index)=><article key={item.id}><b>{item.name}</b><span>★★★★★</span><p>5.0 on Amazon · {index===1?1:3} rating{index===1?"":"s"}</p><a href={item.amazon} target="_blank">View listing ↗</a></article>)}</div><div className="house-portraits"><img src="/media/square/purple-oud-sq.webp" alt="Purple Oud campaign portrait"/><img src="/media/square/humnava-sq.webp" alt="Humnava campaign portrait"/><img src="/media/square/majestic-mogra-sq.webp" alt="Majestic Mogra campaign portrait"/></div><p className="review-note">Amazon exposes the rating totals shown above but not enough publicly retrievable written reviews to quote responsibly. SKF never invents customer endorsements. Customers can submit a verified fragrance story through Instagram.</p><button className="button dark" onClick={()=>openInstagram("Hello SKF! I purchased an SKF fragrance and would like to submit my verified fragrance story for your website. Please tell me what details or photo/video proof you need.")}>Submit your fragrance story ↗</button></section>
    <section className="journal-preview section" id="journal"><div className="journal-heading"><p className="kicker">The SKF journal</p><h2>Fragrance,<br/>with a point of view.</h2><a href="/journal">Enter the journal →</a></div><div className="journal-grid"><a href="/journal#choosing"><img src="/media/square/ethnic-box-sq.webp" alt="Ethnic Series gift box"/><span>Gifting · 6 min</span><h3>The art of choosing a fragrance for someone else</h3><p>Choose a world, not a single note.</p></a><a href="/journal#ritual"><img src="/media/square/humnava-sq.webp" alt="Humnava attar"/><span>Ritual · 4 min</span><h3>Why roll-on attars feel different</h3><p>A slower and more personal way to wear fragrance.</p></a><a href="/journal#layering"><img src="/media/square/regal-sandal-sq.webp" alt="Regal Sandal attar"/><span>Layering · 5 min</span><h3>Building a signature with woods and florals</h3><p>How to layer deliberately without overpowering.</p></a></div></section>
    <section className="discovery section"><div><p className="kicker">Future editions</p><h2>The SKF Discovery Wardrobe.</h2><p>A future miniature sampling ritual designed to let you experience the house before selecting a complete collection. Join the Instagram interest list—no payment or reservation is taken.</p></div><button className="button primary" onClick={()=>openInstagram("Hello SKF! Please add me to the interest list for the future SKF Discovery Wardrobe. I understand this is not a reservation and no payment is required now.")}>Join the interest list ↗</button></section>
    <ScentConcierge/>
    <section className="faq section" id="faq"><div><p className="kicker">Attar guide</p><h2>Questions,<br/>answered.</h2></div><div className="faq-list"><details><summary>What is an alcohol-free attar?</summary><p>Attar is a concentrated fragrance traditionally worn directly on pulse points. SKF collections use roll-on application and are marketed as non-alcoholic attar gift sets.</p></details><details><summary>How much attar is included?</summary><p>Every gift set contains three 6 ml bottles, totalling 18 ml. Each fragrance is also available individually as a 6 ml SKU through prepaid Instagram ordering.</p></details><details><summary>Can I build my own trio?</summary><p>Yes. Select any three individual attars using the bespoke trio builder. The final prepaid amount and exclusive trio discount are confirmed through Instagram.</p></details><details><summary>Are SKF attars for men or women?</summary><p>All Aura, Ethnic and Sovereign compositions are designed as unisex fragrances. Choose by mood and character rather than gender.</p></details><details><summary>Where can I buy Shah Kripa Fragrances?</summary><p>The three gift collections are available on Amazon India. Gift sets and individual bottles can also be ordered through the official Instagram account @skfragrances.in.</p></details></div></section>
    <footer><div className="footer-brand"><img src="/media/logo-gold.webp" alt="Shah Kripa Fragrances"/><p>Essence of Nature.<br/>Purity of Attar.</p></div><div><b>Explore</b><a href="#collection">Gift collections</a><a href="#individual-bottles">Individual attars</a><a href="#scent-finder">Scent finder</a><a href="/journal">Journal</a></div><div><b>Boutique services</b><a href="#build-a-trio">Build a trio</a><a href="#gifting">Gifting studio</a><a href="#concierge">Scent concierge</a><a href="#fragrance-map">Fragrance map</a></div><div><b>Connect</b><a href="https://www.instagram.com/skfragrances.in/" target="_blank">Instagram ↗</a><a href="mailto:skfragrances.in@gmail.com">skfragrances.in@gmail.com</a><span>Ambala, Haryana 134003</span></div><div className="legal"><span>© 2026 Shah Kripa Fragrances</span><span>GSTIN: 06ALEPD3412G1ZR</span><span>Udyam: UDYAM-HR-01-0067231</span><span>House No. 392, Sonia Colony, Manav Chowk, Ambala, Haryana 134003</span></div></footer>
    <div className={cartOpen?"drawer-backdrop show":"drawer-backdrop"} onClick={()=>setCartOpen(false)}/><aside className={cartOpen?"cart-drawer open":"cart-drawer"} aria-label="Instagram shopping bag"><div className="drawer-head"><div><p className="kicker">Prepaid private order</p><h2>Instagram bag</h2></div><button onClick={()=>setCartOpen(false)}>×</button></div>{!qty?<div className="empty-bag"><span>✦</span><h3>Your bag is waiting.</h3><p>Add a gift set or individual bottle to unlock the prepaid Instagram ordering flow.</p><button className="button dark" onClick={()=>setCartOpen(false)}>Explore fragrances</button></div>:<><div className="bag-items">{liveCatalog.filter(item=>cart[item.id]).map(item=><div className="bag-item" key={item.id}><img src={item.image} alt=""/><div><h3>{item.name}</h3><p>{item.series} · {item.size}</p><strong>{money(item.price)}</strong><div className="quantity"><button onClick={()=>update(item.id,-1)}>−</button><span>{cart[item.id]}</span><button onClick={()=>update(item.id,1)}>+</button></div></div></div>)}</div><div className="bag-summary"><div><span>Listed total</span><strong>{money(total)}</strong></div><small>Instagram orders are prepaid only. The exclusive discount and final payable amount are confirmed in DM before payment.</small><button className="button instagram" onClick={order}>{copied?"Message copied — open Instagram ↗":"Get prepaid Instagram offer ↗"}</button><p>Your order text is copied automatically. Paste it if Instagram does not prefill it.</p></div></>}</aside>
    <div className="mobile-buy-bar"><span><small>Private ordering</small>Need help choosing?</span><button onClick={()=>document.getElementById("scent-finder")?.scrollIntoView({behavior:"smooth"})}>Find my attar</button><button onClick={()=>setCartOpen(true)}>Bag {qty?`(${qty})`:""}</button></div>
  </main>;
}
