"use client";

import { useMemo, useState } from "react";
import { giftSets, individualAttars, type CatalogItem, money } from "../lib/catalog";
import { createOrderDraft } from "../lib/order-draft-client";

async function openInstagram(message:string){
  try{await navigator.clipboard.writeText(message)}catch{}
  window.open("https://ig.me/m/skfragrances.in","_blank","noopener,noreferrer");
}

const quizQuestions=[
  {label:"What should your fragrance feel like?",answers:[{text:"Quiet and grounded",series:"ethnic"},{text:"Magnetic and modern",series:"aura"},{text:"Distinctive and regal",series:"sovereign"}]},
  {label:"Which world draws you in?",answers:[{text:"Sandalwood, flowers, tradition",series:"ethnic"},{text:"Amber, oud, dark woods",series:"aura"},{text:"Musk, fresh florals, warm woods",series:"sovereign"}]},
  {label:"Where will you wear it most?",answers:[{text:"Daily ritual and gifting",series:"ethnic"},{text:"Office to evening",series:"aura"},{text:"Celebrations and occasions",series:"sovereign"}]},
] as const;

export function SignatureQuiz({products=giftSets}:{products?:CatalogItem[]}){
  const [step,setStep]=useState(0);const [scores,setScores]=useState<Record<string,number>>({aura:0,ethnic:0,sovereign:0});
  const result=step>=quizQuestions.length?products.find(item=>item.seriesId===Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0]):undefined;
  const choose=(series:string)=>{setScores(s=>({...s,[series]:(s[series]||0)+1}));setStep(v=>v+1)};
  const reset=()=>{setStep(0);setScores({aura:0,ethnic:0,sovereign:0})};
  return <section className="quiz section" id="scent-finder"><div className="quiz-intro"><p className="kicker">SKF private consultation</p><h2>Find your<br/>signature attar.</h2><p>Three intuitive questions. One fragrance world chosen around the presence you want to leave.</p><span>{String(Math.min(step+1,3)).padStart(2,"0")} / 03</span></div><div className="quiz-card">{!result?<><p className="quiz-question">{quizQuestions[step].label}</p><div className="quiz-answers">{quizQuestions[step].answers.map(answer=><button key={answer.text} onClick={()=>choose(answer.series)}><span>✦</span>{answer.text}<b>→</b></button>)}</div></>:<div className={`quiz-result ${result.seriesId}`}><img src={result.image} alt={result.name}/><div><p className="kicker">Your fragrance world</p><h3>{result.name}</h3><p>{result.description}</p><strong>{money(result.price)}</strong><div><a className="button dark" href={`/products/${result.id}`}>Explore the collection</a><button className="text-button" onClick={reset}>Retake quiz</button></div></div></div>}</div></section>;
}

export function TrioBuilder({products=individualAttars}:{products?:CatalogItem[]}){
  const [selected,setSelected]=useState<string[]>([]);
  const items=selected.map(id=>products.find(item=>item.id===id)!).filter(Boolean);
  const total=items.reduce((sum,item)=>sum+item.price,0);
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(v=>v!==id):current.length<3?[...current,id]:current);
  const order=async()=>{const draft=await createOrderDraft(items.map((item)=>({id:item.id,quantity:1})),"custom-trio");const reference=draft?`\n\nSKF order reference: ${draft.reference}`:"";await openInstagram(`Hello Shah Kripa Fragrances! I would like to order a prepaid Build Your Own Trio:\n\n${items.map((item,index)=>`${index+1}. ${item.name} — ${item.series} (${item.size})`).join("\n")}\n\nListed total: ${money(total)}\nPlease confirm the exclusive trio discount, final prepaid amount, gift options and delivery details.${reference}`)};
  return <section className="trio-builder section" id="build-a-trio"><div className="builder-heading"><p className="kicker">The bespoke counter</p><h2>Build your own trio.</h2><p>Select any three individual attars across the house. Your choice becomes a personal SKF wardrobe.</p></div><div className="trio-layout"><div className="trio-options">{products.map(item=>{const active=selected.includes(item.id);return <button className={active?"selected":""} disabled={(!active&&selected.length===3)||item.stockStatus==="paused"} onClick={()=>toggle(item.id)} key={item.id}><img src={item.image} alt=""/><span><small>{item.series}</small><b>{item.name}</b><em>{item.stockStatus==="paused"?"Temporarily unavailable":money(item.price)}</em></span><i>{active?"✓":"+"}</i></button>})}</div><aside className="trio-summary"><p className="kicker">Your composition</p><div className="trio-slots">{[0,1,2].map(index=><div className={items[index]?"filled":""} key={index}>{items[index]?<><img src={items[index].image} alt=""/><span>{items[index].name}</span></>:<><b>0{index+1}</b><span>Select an attar</span></>}</div>)}</div><div className="trio-total"><span>{selected.length} of 3 selected</span><strong>{selected.length?money(total):"—"}</strong></div><button className="button primary" disabled={selected.length!==3} onClick={order}>Order custom trio on Instagram ↗</button><small>Prepaid Instagram order. The exclusive trio discount and final amount are confirmed before payment.</small></aside></div></section>;
}

export function GiftingStudio(){
  const [recipient,setRecipient]=useState("Aarav");const [occasion,setOccasion]=useState("A moment worth remembering");const [message,setMessage]=useState("May this fragrance become part of your finest memories.");const [wrap,setWrap]=useState("Emerald & gold");
  const send=()=>openInstagram(`Hello Shah Kripa Fragrances! I would like a prepaid personalised gift order.\n\nRecipient: ${recipient}\nOccasion: ${occasion}\nGift message: ${message}\nPresentation: ${wrap}\n\nPlease confirm available collection options, final amount and delivery details.`);
  return <section className="gifting-studio section" id="gifting"><div className="gift-form"><p className="kicker">Luxury gifting studio</p><h2>Make the gesture personal.</h2><label>Recipient name<input maxLength={24} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>Occasion<select value={occasion} onChange={e=>setOccasion(e.target.value)}><option>A moment worth remembering</option><option>Birthday</option><option>Wedding</option><option>Anniversary</option><option>Festive celebration</option><option>Corporate gifting</option></select></label><label>Your message<textarea maxLength={120} value={message} onChange={e=>setMessage(e.target.value)}/><small>{message.length}/120</small></label><div className="wrap-options" aria-label="Gift presentation">{["Emerald & gold","Ivory & rose","Midnight & gold"].map(option=><button className={wrap===option?"active":""} onClick={()=>setWrap(option)} key={option}>{option}</button>)}</div><button className="button dark" onClick={send}>Request this gift on Instagram ↗</button></div><div className={`gift-preview ${wrap.split(" ")[0].toLowerCase()}`}><div className="gift-card-preview"><img src="/media/logo-gold.webp" alt=""/><p>For</p><h3>{recipient||"Your recipient"}</h3><i/><blockquote>{message||"Your personal message appears here."}</blockquote><span>{occasion}</span><small>Shah Kripa Fragrances</small></div><p>Live gift-card preview · Final physical presentation is confirmed in DM</p></div></section>;
}

export function ScentMap({products=individualAttars}:{products?:CatalogItem[]}){
  const [active,setActive]=useState(products[0].id);const selected=products.find(item=>item.id===active)??products[0];
  return <section className="scent-map section" id="fragrance-map"><div className="map-copy"><p className="kicker">The fragrance compass</p><h2>Find where your instinct lives.</h2><p>Explore the house by character. Positioning is an interpretive guide based on the descriptions printed on SKF packaging; exact formulas remain proprietary.</p><div className="map-selected"><span>{selected.series}</span><h3>{selected.name}</h3><p>{selected.scent}</p><a href={`/products/${selected.id}`}>View fragrance →</a></div></div><div className="map-board"><span className="axis axis-top">Bold</span><span className="axis axis-bottom">Soft</span><span className="axis axis-left">Floral</span><span className="axis axis-right">Woody</span><i className="map-line vertical"/><i className="map-line horizontal"/>{products.map((item,index)=><button style={{left:`${10+item.character[1]*.78}%`,top:`${92-item.character[0]*.82}%`}} className={`${item.seriesId} ${active===item.id?"active":""}`} onClick={()=>setActive(item.id)} key={item.id} aria-label={`Explore ${item.name}`}><span>{index+1}</span><b>{item.name}</b></button>)}</div></section>;
}

export function ScentConcierge(){
  const [forWhom,setForWhom]=useState("myself");const [profile,setProfile]=useState("woody and warm");const [moment,setMoment]=useState("an everyday signature");
  const message=useMemo(()=>`Hello SKF Scent Stylist! I am choosing an attar for ${forWhom}. I prefer something ${profile}, mainly for ${moment}. Please recommend the best collection or individual 6 ml attar and share the prepaid Instagram offer.`,[forWhom,profile,moment]);
  return <section className="concierge section" id="concierge"><div><p className="kicker">The private counter</p><h2>Speak to an SKF<br/>Scent Stylist.</h2><p>Tell us three things. Your preference is placed into a ready-to-send private consultation message.</p></div><div className="concierge-form"><label>I am choosing for<select value={forWhom} onChange={e=>setForWhom(e.target.value)}><option>myself</option><option>a partner</option><option>a family member</option><option>a friend</option><option>a corporate gift</option></select></label><label>I prefer something<select value={profile} onChange={e=>setProfile(e.target.value)}><option>woody and warm</option><option>floral and soft</option><option>fresh and vibrant</option><option>dark and mysterious</option><option>regal and expressive</option></select></label><label>The main moment is<select value={moment} onChange={e=>setMoment(e.target.value)}><option>an everyday signature</option><option>office and meetings</option><option>evenings and events</option><option>festive occasions</option><option>thoughtful gifting</option></select></label><button className="button primary" onClick={()=>openInstagram(message)}>Start private consultation ↗</button><small>Your consultation text is copied automatically before Instagram opens.</small></div></section>;
}
