"use client";

import { type PointerEvent, useEffect, useRef, useState } from "react";
import { CatalogItem, catalog, money } from "../lib/catalog";
import { createOrderDraft } from "../lib/order-draft-client";

export default function ProductDetailClient({item}:{item:CatalogItem}){
  const [active,setActive]=useState(0);const [rotation,setRotation]=useState(0);const [open,setOpen]=useState(false);const [saved,setSaved]=useState(false);const [recent,setRecent]=useState<CatalogItem[]>([]);const dragging=useRef<{x:number;rotation:number}|null>(null);
  const related=catalog.filter(product=>product.seriesId===item.seriesId&&product.id!==item.id).slice(0,3);
  useEffect(()=>{try{const ids=JSON.parse(localStorage.getItem("skf-recent")||"[]") as string[];setRecent(ids.filter(id=>id!==item.id).map(id=>catalog.find(product=>product.id===id)!).filter(Boolean).slice(0,3));localStorage.setItem("skf-recent",JSON.stringify([item.id,...ids.filter(id=>id!==item.id)].slice(0,4)));const wishes=JSON.parse(localStorage.getItem("skf-wishlist")||"[]") as string[];setSaved(wishes.includes(item.id))}catch{}},[item.id]);
  const wish=()=>{setSaved(value=>{const next=!value;try{const wishes=JSON.parse(localStorage.getItem("skf-wishlist")||"[]") as string[];localStorage.setItem("skf-wishlist",JSON.stringify(next?[...new Set([...wishes,item.id])]:wishes.filter(id=>id!==item.id)))}catch{}return next})};
  const start=(event:PointerEvent<HTMLDivElement>)=>{dragging.current={x:event.clientX,rotation};event.currentTarget.setPointerCapture(event.pointerId)};
  const move=(event:PointerEvent<HTMLDivElement>)=>{if(!dragging.current)return;setRotation(dragging.current.rotation+(event.clientX-dragging.current.x)*.24)};
  const end=()=>{dragging.current=null};
  const instagram=async()=>{const draft=await createOrderDraft([{id:item.id,quantity:1}],"product-page");const reference=draft?` SKF order reference: ${draft.reference}.`:"";const message=`Hello Shah Kripa Fragrances! I would like to place a prepaid order for ${item.name} (${item.series}, ${item.size}) at the listed price of ${money(item.price)}.${reference} Please confirm the exclusive Instagram discount, final amount, availability and delivery details.`;try{await navigator.clipboard.writeText(message)}catch{}window.open("https://ig.me/m/skfragrances.in","_blank","noopener,noreferrer")};
  return <main className={`product-page theme-${item.seriesId}`}>
    <header className="product-nav"><a href="/" className="brand"><img src="/media/logo-gold.webp" alt=""/><span>SHAH KRIPA <small>FRAGRANCES</small></span></a><a href="/#individual-bottles">← Back to the house</a></header>
    <section className="product-hero"><div className="product-gallery"><div className="product-main-image"><img key={item.gallery[active]} src={item.gallery[active]} alt={`${item.name} product view ${active+1}`}/><span>{String(active+1).padStart(2,"0")} / {String(item.gallery.length).padStart(2,"0")}</span></div><div className="product-thumbs">{item.gallery.map((image,index)=><button className={active===index?"active":""} onClick={()=>setActive(index)} key={image}><img src={image} alt=""/></button>)}</div></div><div className="product-overview"><p className="kicker">{item.series} · {item.kind}</p><h1>{item.name}</h1><p className="product-profile">{item.scent}</p><p className="product-description">{item.description}</p><dl><div><dt>Character</dt><dd>{item.mood}</dd></div><div><dt>Best for</dt><dd>{item.occasion}</dd></div><div><dt>Format</dt><dd>{item.size} roll-on</dd></div><div><dt>Expression</dt><dd>Alcohol-free · Unisex</dd></div></dl><div className="product-price"><strong>{money(item.price)}</strong>{item.mrp&&<s>{money(item.mrp)}</s>}</div><small>{item.stockStatus==="paused"?"Temporarily unavailable":item.kind==="Gift Set"?"Amazon selling price · inclusive of all taxes":"Individual prepaid Instagram order"}</small><div className="product-actions">{item.amazon&&item.stockStatus!=="paused"&&<a className="button primary" href={item.amazon} target="_blank">Buy on Amazon ↗</a>}<button className="button dark" disabled={item.stockStatus==="paused"} onClick={instagram}>{item.stockStatus==="paused"?"Temporarily unavailable":"Order on Instagram ↗"}</button><button className={`save-button ${saved?"active":""}`} onClick={wish}>{saved?"♥ Saved":"♡ Save fragrance"}</button></div></div></section>
    <section className="bottle-interaction section"><div><p className="kicker">A closer ritual</p><h2>Hold the bottle.<br/>Open the experience.</h2><p>Drag horizontally to turn the bottle. Use the control to lift the cap and reveal the roll-on ritual.</p><button className="button outline" onClick={()=>setOpen(value=>!value)}>{open?"Close the bottle":"Lift the cap"} {open?"↓":"↑"}</button></div><div className={`interactive-bottle ${open?"open":""}`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} style={{"--rotation":`${rotation}deg`} as React.CSSProperties}><div className="bottle-glow"/><img className="bottle-body-layer" src={item.image} alt="" draggable={false}/><img className="bottle-cap-layer" src={item.image} alt="" draggable={false}/><span>← drag to rotate →</span></div></section>
    <section className="product-character section"><div><p className="kicker">Fragrance character</p><h2>{item.mood}</h2><p>{item.description} Wear lightly on pulse points, then allow body warmth to reveal the composition at its own pace.</p></div><div className="character-bars"><label>Floral <i><span style={{width:`${item.character[0]}%`}}/></i><b>{item.character[0]}</b></label><label>Bold <i><span style={{width:`${item.character[1]}%`}}/></i><b>{item.character[1]}</b></label><label>Warm <i><span style={{width:`${item.character[2]}%`}}/></i><b>{item.character[2]}</b></label><small>Interpretive character guide—not a disclosure of the proprietary formula.</small></div></section>
    <section className="application-ritual section"><p className="kicker">The application ritual</p><div><article><b>01</b><h3>Touch</h3><p>Roll once onto wrists or the sides of the neck.</p></article><article><b>02</b><h3>Pause</h3><p>Do not rub. Let warmth unfold the fragrance naturally.</p></article><article><b>03</b><h3>Layer</h3><p>Combine with a complementary SKF attar for a personal signature.</p></article></div></section>
    <section className="related section"><div><p className="kicker">Continue the journey</p><h2>From the same world.</h2></div><div>{related.map(product=><a href={`/products/${product.id}`} key={product.id}><img src={product.image} alt=""/><span>{product.kind}</span><h3>{product.name}</h3><strong>{money(product.price)}</strong></a>)}</div></section>
    {recent.length>0&&<section className="recently-viewed section"><div><p className="kicker">Your fragrance trail</p><h2>Recently viewed.</h2></div><div>{recent.map(product=><a href={`/products/${product.id}`} key={product.id}><img src={product.image} alt=""/><span>{product.series}</span><h3>{product.name}</h3></a>)}</div></section>}
    <footer className="product-footer"><a href="/">Shah Kripa Fragrances</a><span>GSTIN: 06ALEPD3412G1ZR</span><a href="https://www.instagram.com/skfragrances.in/" target="_blank">@skfragrances.in ↗</a></footer>
    <div className="product-mobile-bar"><span><small>{item.name}</small>{money(item.price)}</span>{item.stockStatus==="paused"?<button disabled>Unavailable</button>:item.amazon?<a href={item.amazon} target="_blank">Buy on Amazon</a>:<button onClick={instagram}>Order on Instagram</button>}</div>
  </main>;
}
